
before_script:
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz

build_test:
  script:
    - echo Testing an app with multiple services in it causes network problems on circle
    - echo revisit this with gitlab


deploy:
  stage: deploy
  only:
    refs:
        - master
  script:
    - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack turnkey-service-php --file scripts/docker-compose.yml --rancher-file rancher-compose.yml
