
before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  # Atm, we are not using docker....
  # - mkdir -p $HOME/.docker
  # - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  # - set -x

# variables:
#   DB_HOST: ireceptor-database
#   DB_DATABASE: ireceptor
#   DB_SAMPLES_COLLECTION: sample
#   DB_SEQUENCES_COLLECTION: sequence


stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python3 build_helper.py scripts/docker-compose.yml > /dev/null
    - echo TBD

deploy:
  stage: deploy
  only:
    refs:
        - production-v3
# TODO REMOVE THIS vvvv !
        - migrate-to-swarm
# TODO REMOVE THIS ^^^^ !
  script:
    - sleep 15
    - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    - chmod 0400 ./sc_swarm_cicd_ssh_key
    - python3 build_helper.py scripts/docker-compose.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - turnkey-service-php
