version: '3.3'

services:

    ireceptor-database:
        networks:
        - proxy
    # the interpolation in the upstream docker-compose.yml does not
    # seem to work in this version of docker-compose, so the image tags
    # are hardcoded here.
        image: ireceptor/repository-mongodb:turnkey-v3
        deploy:
            placement:
                constraints: [node.labels.persistent_data == true]
            restart_policy:
                condition: on-failure
        volumes:
            - ireceptor_turnkey_mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: ireceptor

    ireceptor-api:
        depends_on:
            - ireceptor-database
        networks:
        - proxy
        # image tag hardcoded:
        image: ireceptor/service-php-mongodb:turnkey-v3
        deploy:
            placement:
                constraints: [node.labels.persistent_data == true]
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.turnkey-service-php.rule=Host(`ireceptor.fredhutch.org`)"
                - "traefik.http.routers.turnkey-service-php-secured.rule=Host(`ireceptor.fredhutch.org`)"
                - "traefik.http.routers.turnkey-service-php.entrypoints=web,web-secured"
                - "traefik.http.services.turnkey-service-php.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
                - "traefik.http.routers.turnkey-service-php.tls=true"
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence


volumes:
  ireceptor_turnkey_mongodb_data:
    external: true

networks:
  proxy:
    external: true
