version: '3'

services:

    ireceptor-database:
        image: ireceptor/repository-mongodb:${DATABASE_TAG:-turnkey}
        volumes:
            - ../.mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: ireceptor

    ireceptor-api:
        depends_on:
            - ireceptor-database
        image: ireceptor/service-php-mongodb:${API_TAG:-turnkey}
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence
        ports:
            - 80:80

    ireceptor-dataloading:
        depends_on:
            - ireceptor-database
        image: ireceptor/dataloading-mongo:${DATALOADING_TAG:-turnkey}
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
        volumes:
            - ${FILE_FOLDER:-/tmp}:/scratch:ro

    ireceptor-performance-testing:
        image: ireceptor/dataloading-mongo:${PERFORMANCE_TESTING_TAG:-turnkey-refactor-mongo}
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
