# IMPORTANT: Version needs to be '2' for deployment
# though it is '3' in upstream repos
version: '2'

services:

    ireceptor-database:
    # the interpolation in the upstream docker-compose.yml does not
    # seem to work in this version of docker-compose, so the image tags
    # are hardcoded here.
        image: ireceptor/repository-mongodb:turnkey-v3
        labels:
          io.rancher.container.pull_image: always
          name: "scicomp-ext-a1"
          io.rancher.scheduler.affinity:host_label: name=scicomp-a1
        volumes:
            - mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: ireceptor

    ireceptor-api:
        depends_on:
            - ireceptor-database
        # image tag hardcoded:
        image: ireceptor/service-php-mongodb:turnkey-v3
        labels:
          io.rancher.container.pull_image: always
          name: "scicomp-ext-a1"
          io.rancher.scheduler.affinity:host_label: name=scicomp-a1
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence
        ports:
            # interpolated host port hardcoded, changed from 80 to
            # 8033
            - 8033:80

    ireceptor-dataloading:
        labels:
          io.rancher.container.pull_image: always
          name: "scicomp-ext-a1"
          io.rancher.scheduler.affinity:host_label: name=scicomp-a1
        depends_on:
            - ireceptor-database
        image: ireceptor/dataloading-mongo:turnkey-v3-dataloading
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
        volumes:
            - loadingvolume:/scratch
        restart: "no"

    ireceptor-performance-testing:
        labels:
          io.rancher.container.pull_image: always
          name: "scicomp-ext-a1"
          io.rancher.scheduler.affinity:host_label: name=scicomp-a1
        # image tag hardcoded:
        image: ireceptor/dataloading-mongo:turnkey-v3-performance
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: ireceptor
            DB_SAMPLES_COLLECTION: sample
            DB_SEQUENCES_COLLECTION: sequence

volumes:
  loadingvolume: {}
  mongodb_data: {}

