version: '3'

services:

    ireceptor-database:
        image: ireceptorj/repository-mongodb:dev
        volumes:
            - ../.mongodb_data:/data/db

    ireceptor-api:
        depends_on:
            - ireceptor-database
        image: ireceptorj/service-php-mongodb:latest
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: test
        ports:
            - 80:80

    ireceptor-dataloading:
        depends_on:
            - ireceptor-database
        image: ireceptorj/dataloading-mongo:dev
        environment:
            DB_HOST: ireceptor-database
            DB_DATABASE: test
        volumes:
            - ${FILE_FOLDER:-/tmp}:/scratch:ro
